// Frontend/src/components/Workbook.tsx
import React from 'react';
import './Workbook.css';

const Workbook: React.FC = () => {
    return (
        <div className="page-container">
            <header className="page-header">
                <h1 className="title">Learning Workbook</h1>
                <p className="subtitle">Mastering React, FastAPI, and Supabase integration.</p>
            </header>

            <div className="cards-grid">
                <div className="info-card glass-panel interactive-card">
                    <div className="card-icon">⚛️</div>
                    <h3>React Frontend</h3>
                    <p>Modern component-based UI library for building Single Page Applications. Learn about hooks, routing, and state management.</p>
                </div>

                <div className="info-card glass-panel interactive-card">
                    <div className="card-icon">⚡</div>
                    <h3>FastAPI Backend</h3>
                    <p>High performance Python web framework. Explore asynchronous endpoints, automatic docs (Redoc), and serverless execution.</p>
                </div>

                <div className="info-card glass-panel interactive-card">
                    <div className="card-icon">🗄️</div>
                    <h3>Supabase</h3>
                    <p>Open source Firebase alternative. Manage your database, authentication, and edge functions natively using PostgreSQL.</p>
                </div>
            </div>

            <div className="content-section glass-panel">
                <h2>System Architecture</h2>
                <div className="architecture-diagram">
                    <div className="node react">React App (Webpack)</div>
                    <div className="connector">→ Proxy API →</div>
                    <div className="node fastapi">FastAPI (Netlify Functions)</div>
                    <div className="connector">→ SDK →</div>
                    <div className="node supabase">Supabase DB</div>
                </div>
            </div>
        </div>
    );
};

export default Workbook;

// Frontend/src/app/workbook/workbook.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-workbook',
  template: `
    <div class="page-container animate-fade-in">
      <header class="page-header">
        <h1 class="title">Learning Workbook</h1>
        <p class="subtitle">Mastering Angular, FastAPI, and Supabase integration.</p>
      </header>

      <div class="cards-grid">
        <div class="info-card glass-panel interactive-card">
          <div class="card-icon">🅰️</div>
          <h3>Angular Frontend</h3>
          <p>Modern component-based UI framework for building robust applications. Learn about modules, services, and RxJS.</p>
        </div>

        <div class="info-card glass-panel interactive-card">
          <div class="card-icon">⚡</div>
          <h3>FastAPI Backend</h3>
          <p>High performance Python web framework. Explore asynchronous endpoints, automatic docs (Redoc), and serverless execution.</p>
        </div>

        <div class="info-card glass-panel interactive-card">
          <div class="card-icon">🗄️</div>
          <h3>Supabase</h3>
          <p>Open source Firebase alternative. Manage your database, authentication, and edge functions natively using PostgreSQL.</p>
        </div>
      </div>

      <div class="content-section glass-panel">
        <h2>System Architecture</h2>
        <div class="architecture-diagram">
          <div class="node angular">Angular App (Webpack)</div>
          <div class="connector">→ Proxy API →</div>
          <div class="node fastapi">FastAPI (Netlify Functions)</div>
          <div class="connector">→ SDK →</div>
          <div class="node supabase">Supabase DB</div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .page-container { max-width: 1000px; margin: 0 auto; }
    .page-header { text-align: center; margin-bottom: 3rem; }
    .title {
      font-size: 3rem;
      background: linear-gradient(135deg, #60A5FA, #A78BFA);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 1rem;
    }
    .subtitle { font-size: 1.25rem; color: var(--text-muted); }
    .cards-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 2rem;
      margin-bottom: 3rem;
    }
    .info-card { padding: 2rem; text-align: center; }
    .interactive-card { transition: transform 0.3s ease, box-shadow 0.3s ease; cursor: default; }
    .interactive-card:hover {
      transform: translateY(-8px);
      box-shadow: 0 12px 40px rgba(0, 0, 0, 0.2);
      border-color: rgba(255, 255, 255, 0.2);
    }
    .card-icon { font-size: 3rem; margin-bottom: 1rem; }
    .info-card h3 { font-size: 1.5rem; margin-bottom: 1rem; color: #fff; }
    .info-card p { color: var(--text-muted); font-size: 0.95rem; }
    .content-section { padding: 3rem; text-align: center; }
    .content-section h2 { font-size: 2rem; margin-bottom: 2rem; }
    .architecture-diagram { display: flex; align-items: center; justify-content: center; flex-wrap: wrap; gap: 1rem; margin-top: 2rem; }
    .node { padding: 1rem 1.5rem; border-radius: 8px; font-weight: 600; font-size: 1.1rem; }
    .node.angular { background: rgba(221, 0, 49, 0.15); border: 1px solid #DD0031; color: #FF2B5C; }
    .node.fastapi { background: rgba(5, 153, 139, 0.15); border: 1px solid #05998b; color: #38E3D2; }
    .node.supabase { background: rgba(62, 207, 142, 0.15); border: 1px solid #3ECF8E; color: #8CFFC7; }
    .connector { color: var(--text-muted); font-weight: bold; }
  `]
})
export class WorkbookComponent {}
